apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-storage-class
provisioner: rancher.io/local-path
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proj-config
data:
  MYSQL_DATABASE: "db"
  MYSQL_USER: "admin" #cannot be root
  PMA_HOST: "mysql-service"
  PMA_USER: "admin" #cannot be root
---
apiVersion: v1
kind: Secret
metadata:
  name: proj-secret
type: Opaque
data:
  MYSQL_PASSWORD: ZXhhbXBsZQ== #example
  MYSQL_ROOT_PASSWORD: ZXhhbXBsZQ== #example
  PMA_PASSWORD: ZXhhbXBsZQ== #example
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pma-pv
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    path: /tmp/pma-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pma-pvc
spec:
  storageClassName: ""
  volumeName: pma-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        worker: node01
      containers:
        - name: mysql
          image: elestio/mysql
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: proj-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: proj-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: proj-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: proj-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-volume
      spec:
        storageClassName: my-storage-class
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  clusterIP: None
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      nodeSelector:
        worker: node01
      containers:
        - name: phpmyadmin
          image: phpmyadmin:latest
          env:
            - name: PMA_USER
              valueFrom:
                configMapKeyRef:
                  name: proj-config
                  key: PMA_USER
            - name: PMA_HOST
              valueFrom:
                configMapKeyRef:
                  name: proj-config
                  key: PMA_HOST
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: proj-secret
                  key: PMA_PASSWORD
          volumeMounts:
            - name: phpmyadmin-vol
              mountPath: /data/phpmyadmin-vol
          ports:
            - containerPort: 80
              name: phpmyadmin
      volumes:
        - name: phpmyadmin-vol
          persistentVolumeClaim:
            claimName: pma-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin-service
spec:
  ports:
    - port: 80
      name: phpmyadmin-service
  type: NodePort
  selector:
    app: phpmyadmin
