apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: new-usercluster-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumes", "configmaps", "secrets"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-resources-manager-binding
subjects:
  - kind: User
    name: new-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: new-usercluster-role
  apiGroup: rbac.authorization.k8s.io
